services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-api-gateway
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: payement_db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "10042:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springboot-app-gateway
    ports:
      - "10041:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/payement_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SHOW_SQL=false
      - DDL_AUTO=validate
